# Generated by Django 5.1 on 2024-08-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "report_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Pending"), (1, "Completed")]),
                ),
                (
                    "report_url",
                    models.FileField(blank=True, null=True, upload_to="reports"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreZone",
            fields=[
                (
                    "store_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "timezone_str",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time Stamp in UTC"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="api.storezone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dayOfWeek", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="api.storezone",
                    ),
                ),
            ],
        ),
    ]
